Better runit service management

diff --git a/containers/docker/runit/spampd/run b/containers/docker/runit/spampd/run
--- a/containers/docker/runit/spampd/run
+++ b/containers/docker/runit/spampd/run
@@ -1,16 +1,42 @@
 #!/bin/bash
-
+PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
+DESC='spam checking proxy daemon'
 NAME='spampd'
 PROGRAM=/usr/sbin/spampd
+#EXECUTABLE=`head -n 1 $PROGRAM | sed -e 's,^#![ 	]*/,/,;s,[ 	].*$,,'`
+EXECUTABLE=/usr/bin/perl
+PIDFILE=/var/run/spampd.pid
+
+if [ -f $PIDFILE ]; then
+	# If can't delete pidfile, this means process is running ...
+	rm $PIDFILE || exit 0
+fi
+
+. /lib/lsb/init-functions
+
+# set some important defaults (overridable via /etc/default/spampd)
+USERID=spampd
+GRPID=spampd
 
 if [ -f /etc/default/$NAME ]; then
-        . /etc/default/$NAME
+	. /etc/default/$NAME
 fi
 
 istrue () {
     ANS=$(echo $1 | tr A-Z a-z)
     [ "$ANS" = 'yes' -o "$ANS" = 'true' -o "$ANS" = 'enable' -o "$ANS" = '1' ]
 }
+
+#
+# find out wether to start spampd or not
+#
+istrue ${STARTSPAMPD} && STARTSPAMPD='true'
+
+#
+# Check wether the program is actually there
+#
+# return 5 as demanded by LSB 2.1 when program isn't installed.
+[  -x $PROGRAM ] || exit 5
 
 #
 # Calculate final commandline
@@ -57,4 +83,16 @@ ARGS="${S_LOCALONLY} ${S_AWL} ${S_TAGALL} "
 # Don't daemonize
 ARGS="${ARGS} --nodetach"
 
-exec $PROGRAM $ARGS 2>&1
+if ! istrue "${STARTSPAMPD}"; then
+	log_warning_msg "Starting $DESC: $NAME (disabled in /etc/default/$NAME)."
+	# LSB 2.1: 6 mean unconfigured. This seems appropriate here.
+	exit 6
+fi
+log_daemon_msg "Starting $DESC" "$NAME"
+# if spampd is not installed, return 5 as demanded by LSB 2.1
+if [ ! -x $EXECUTABLE ]; then
+	log_error_msg "failed! - executable not found"
+	exit 5
+fi
+# start daemon
+exec $PROGRAM $ARGS
